# This solution works, but is not the only working solution.
# Feel free to do a better job.

task :process_images do
	# get the path to the images
	path = File.join("images", "*")
	
	# get the files
	files = Dir.glob(path)
	
	files.each do |file|
		new_name = ""
		
		# split words on capital letter
		words = File.basename(file).scan(/[A-Z][a-z]+/)
		
		# remove capital letters, concatenate, and add the _ for each word
		words.each { |word|	new_name += "#{word.downcase}_" }
		
		# remove trailing _ and readd the file extension
		new_name = File.join(File.dirname(file), new_name[0...-1] + File.extname(file))
		
		# rename the files
		File.rename(file, new_name)
	end
	
	p 'File Rename Completed'
end